# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3400ce0d1359c74568e588f000edcc59feaa762af365aae1a3fdca912d986633f8f6b264470430600937e34f72e6df703a5319323fbde783873ace63dda8574

test:
  secret_key_base: a8e925fdd41accd793608bc79b14e31b934f25a08d2a98b54edacd83b73f1ada87443a1889378dab24345cd9ba9ff2b24673348cb30c8ac48dc1e30e2dd2a156

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
